-- ByGether - PASO 12 / bloque 2: fuentes de noticias (RSS) por tema para las cuentas automaticas con nombre de persona.
-- Cada feed se probo en vivo (HTTP 200, con entradas recientes) el 2026-09-24. Se evitaron a proposito los medios que ya usan las cuentas canal.
insert into public.fuentes_noticias (tema, nombre, sitio_url, feed_url, ultimo_ok_at) values
('cocina','Directo al Paladar','https://www.directoalpaladar.com','https://www.directoalpaladar.com/index.xml',now()),
('cocina','Recetas de Rechupete','https://www.recetasderechupete.com','https://www.recetasderechupete.com/feed/',now()),
('cocina','Bonviveur','https://www.bonviveur.es','https://www.bonviveur.es/rss',now()),
('música','Indie Hoy','https://www.indiehoy.com','https://www.indiehoy.com/feed/',now()),
('música','Mondo Sonoro','https://www.mondosonoro.com','https://www.mondosonoro.com/feed/',now()),
('música','Hipersónica','https://www.hipersonica.com','https://www.hipersonica.com/feed/',now()),
('música','Efe Eme','https://www.efeeme.com','https://www.efeeme.com/feed/',now()),
('moda','Vogue España','https://www.vogue.es','https://www.vogue.es/feed/rss',now()),
('moda','Vogue México','https://www.vogue.mx','https://www.vogue.mx/feed/rss',now()),
('moda','Harper''s Bazaar España','https://www.harpersbazaar.com/es','https://www.harpersbazaar.com/es/rss/all.xml/',now()),
('moda','Elle España','https://www.elle.com/es','https://www.elle.com/es/rss/all.xml/',now()),
('ciencia','Xataka Ciencia','https://www.xatakaciencia.com','https://www.xatakaciencia.com/index.xml',now()),
('ciencia','Muy Interesante','https://www.muyinteresante.com','https://www.muyinteresante.com/feed/',now()),
('ciencia','La Vanguardia Ciencia','https://www.lavanguardia.com/ciencia','https://www.lavanguardia.com/rss/ciencia.xml',now()),
('ciencia','ABC Ciencia','https://www.abc.es/ciencia','https://www.abc.es/rss/feeds/abc_Ciencia.xml',now()),
('actualidad','Diario Libre','https://www.diariolibre.com','https://www.diariolibre.com/rss/portada.xml',now()),
('actualidad','BBC Mundo','https://www.bbc.com/mundo','https://feeds.bbci.co.uk/mundo/rss.xml',now()),
('actualidad','DW Español','https://www.dw.com/es','https://rss.dw.com/xml/rss-sp-all',now()),
('actualidad','France 24 Español','https://www.france24.com/es','https://www.france24.com/es/rss',now()),
('salud y bienestar','EFE Salud','https://www.efesalud.com','https://www.efesalud.com/feed/',now()),
('salud y bienestar','Saludiario','https://www.saludiario.com','https://www.saludiario.com/feed/',now()),
('salud y bienestar','Cuídate Plus','https://cuidateplus.marca.com','https://cuidateplus.marca.com/feed',now()),
('finanzas personales','El Dinero','https://www.eldinero.com.do','https://www.eldinero.com.do/feed/',now()),
('finanzas personales','El Blog Salmón','https://www.elblogsalmon.com','https://www.elblogsalmon.com/index.xml',now()),
('cine y series','Espinof','https://www.espinof.com','https://www.espinof.com/index.xml',now()),
('cine y series','Fotogramas','https://www.fotogramas.es','https://www.fotogramas.es/rss/all.xml',now()),
('cine y series','SensaCine','https://www.sensacine.com','https://www.sensacine.com/rss/noticias.xml',now()),
('cine y series','Cinemascomics','https://www.cinemascomics.com','https://www.cinemascomics.com/feed/',now()),
('videojuegos','Vida Extra','https://www.vidaextra.com','https://www.vidaextra.com/index.xml',now()),
('videojuegos','Area Jugones','https://www.areajugones.es','https://www.areajugones.es/feed/',now()),
('videojuegos','Eurogamer España','https://www.eurogamer.es','https://www.eurogamer.es/feed',now()),
('emprendimiento','Emprendedores','https://www.emprendedores.es','https://www.emprendedores.es/feed/',now()),
('emprendimiento','IEB School','https://www.iebschool.com/blog','https://www.iebschool.com/blog/feed/',now()),
('emprendimiento','Emprendedores News','https://www.emprendedoresnews.com','https://www.emprendedoresnews.com/feed/',now()),
('emprendimiento','Infoautónomos','https://www.infoautonomos.com/blog','https://www.infoautonomos.com/blog/feed/',now()),
('libros','Zenda','https://www.zendalibros.com','https://www.zendalibros.com/feed/',now()),
('libros','La Vanguardia Cultura','https://www.lavanguardia.com/cultura','https://www.lavanguardia.com/rss/cultura.xml',now()),
('libros','ABC Cultura','https://www.abc.es/cultura','https://www.abc.es/rss/feeds/abc_Cultura.xml',now()),
('libros','elDiario.es Cultura','https://www.eldiario.es/cultura','https://www.eldiario.es/rss/cultura/',now()),
('educación','Educación 3.0','https://www.educaciontrespuntocero.com','https://www.educaciontrespuntocero.com/feed/',now()),
('educación','Magisnet','https://www.magisnet.com','https://www.magisnet.com/feed/',now()),
('educación','Observatorio del Tec de Monterrey','https://observatorio.tec.mx','https://observatorio.tec.mx/feed/',now()),
('mascotas','Animales Mascotas','https://www.animalesmascotas.com','https://www.animalesmascotas.com/feed',now()),
('viajes','Hosteltur','https://www.hosteltur.com','https://www.hosteltur.com/rss',now()),
('viajes','Actualidad Viajes','https://www.actualidadviajes.com','https://www.actualidadviajes.com/feed/',now()),
('viajes','Travel Report','https://www.travelreport.mx','https://www.travelreport.mx/feed',now()),
('viajes','Viajeros Callejeros','https://www.viajeroscallejeros.com','https://www.viajeroscallejeros.com/feed',now()),
('arte y fotografía','Xataka Foto','https://www.xatakafoto.com','https://www.xatakafoto.com/index.xml',now()),
('arte y fotografía','DZoom','https://www.dzoom.org.es','https://www.dzoom.org.es/feed/',now()),
('tecnología','Xataka','https://www.xataka.com','https://www.xataka.com/index.xml',now()),
('tecnología','Genbeta','https://www.genbeta.com','https://www.genbeta.com/index.xml',now()),
('tecnología','Hipertextual','https://www.hipertextual.com','https://www.hipertextual.com/feed',now()),
('tecnología','Applesfera','https://www.applesfera.com','https://www.applesfera.com/index.xml',now()),
('deportes','Mundo Deportivo','https://www.mundodeportivo.com','https://www.mundodeportivo.com/rss/home',now()),
('deportes','Diario Libre Deportes','https://www.diariolibre.com','https://www.diariolibre.com/rss/deportes.xml',now()),
('deportes','Olé','https://www.ole.com.ar','https://www.ole.com.ar/rss/ultimas-noticias/',now()),
('automóviles','Motorpasión','https://www.motorpasion.com','https://www.motorpasion.com/index.xml',now()),
('automóviles','Diariomotor','https://www.diariomotor.com','https://www.diariomotor.com/feed/',now()),
('automóviles','Autobild España','https://www.autobild.es','https://www.autobild.es/rss',now())
on conflict (tema, sitio_url) do nothing;
