-- ============================================================
-- PASO 11: BOTONES FUNCIONALES EN LOS COMENTARIOS
-- (Me gusta, Responder, Repostear, Compartir - igual que en las publicaciones)
-- ============================================================
-- Es seguro ejecutar este script más de una vez.

-- ---------- 1) Respuestas a un comentario ----------
-- Un comentario puede ser respuesta de otro comentario (mismo post, hilo simple).
alter table public.comments
  add column if not exists reply_to bigint references public.comments(id) on delete cascade;

create index if not exists comments_reply_to_idx on public.comments (reply_to);

-- ---------- 2) "Me gusta" en comentarios ----------
create table if not exists public.comment_likes (
  id bigint generated by default as identity primary key,
  comment_id bigint not null references public.comments(id) on delete cascade,
  user_email text not null,
  user_name text,
  created_at timestamptz not null default now()
);

create unique index if not exists comment_likes_unico_por_usuario
  on public.comment_likes (comment_id, user_email);
create index if not exists comment_likes_comment_idx on public.comment_likes (comment_id);

alter table public.comment_likes enable row level security;

drop policy if exists comment_likes_select_public on public.comment_likes;
create policy comment_likes_select_public on public.comment_likes
  for select to public using (true);

drop policy if exists comment_likes_insert_own on public.comment_likes;
create policy comment_likes_insert_own on public.comment_likes
  for insert to public with check (user_email = auth.email());

drop policy if exists comment_likes_delete_own on public.comment_likes;
create policy comment_likes_delete_own on public.comment_likes
  for delete to public using (user_email = auth.email());

-- Cuenta de "me gusta" por comentario (solo lectura, en vivo, igual estilo que comment_counts/repost_counts)
create or replace function public.comment_like_counts(comment_ids bigint[])
returns table (comment_id bigint, total bigint)
language sql stable security invoker set search_path = public as $$
  select cl.comment_id, count(*)::bigint as total
  from public.comment_likes cl
  where cl.comment_id = any(comment_ids)
  group by cl.comment_id;
$$;
grant execute on function public.comment_like_counts(bigint[]) to anon, authenticated;

-- Cuenta de respuestas por comentario (solo lectura, en vivo)
create or replace function public.comment_reply_counts(comment_ids bigint[])
returns table (comment_id bigint, total bigint)
language sql stable security invoker set search_path = public as $$
  select c.reply_to as comment_id, count(*)::bigint as total
  from public.comments c
  where c.reply_to = any(comment_ids)
  group by c.reply_to;
$$;
grant execute on function public.comment_reply_counts(bigint[]) to anon, authenticated;

-- ---------- 3) Repostear un comentario (aparece como publicación en tu perfil, citando el comentario) ----------
alter table public.posts
  add column if not exists repost_of_comment_id bigint references public.comments(id) on delete cascade;

create index if not exists posts_repost_of_comment_idx on public.posts (repost_of_comment_id);

-- Cuenta de reposts por comentario (solo lectura, en vivo)
create or replace function public.comment_repost_counts(comment_ids bigint[])
returns table (comment_id bigint, total bigint)
language sql stable security invoker set search_path = public as $$
  select p.repost_of_comment_id as comment_id, count(*)::bigint as total
  from public.posts p
  where p.repost_of_comment_id = any(comment_ids)
  group by p.repost_of_comment_id;
$$;
grant execute on function public.comment_repost_counts(bigint[]) to anon, authenticated;
